
// This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
export const environment: Environment = {
  production: true,
  API_URL: process.env['API_URL'] || ''
};