
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment: Environment = {
    production: false,
    API_URL: ''
  };
