
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment: Environment = {
    production: true,
    NG_APP_API_URL: import.meta.env['NG_APP_API_URL']
  };