// This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
export const environment: Environment = {
  production: true,
  NG_APP_API_URL: 'https://api.npoint.io/24973a3d86dcd56a6a2b',
};
