name: GitHub Ppages to wandersonareis.io

on:
    push:
        branches:
            - master
permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
          NG_APP_API_URL: ${{ secrets.NG_APP_API_URL }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Build
              run: bun run build

            - name: Deploy
              if: success()
              uses: JamesIves/github-pages-deploy-action@releases/v4
              with:
                branch: gh-pages
                ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                folder: ./dist/resume/browser
                repository-name: wandersonareis/wandersonareis.github.io
